// Generated by CoffeeScript 1.12.7
(function() {
  var data;

  data = {
    fascist_powers: {
      5: [null, null, 'policy_peek', 'execution', 'execution'],
      7: [null, 'investigation', 'special_election', 'execution', 'execution'],
      9: ['investigation', 'investigation', 'special_election', 'execution', 'execution']
    },
    min_players: 5,
    max_players: 10,
    fascist_ratio: 0.45,
    fascist_target_policies: 6,
    liberal_target_policies: 5,
    max_refusals: 3,
    num_liberal_policies: 6,
    num_fascist_policies: 11,
    veto_min_policies: 5,
    hitler_win_min_policies: 3,
    blind_hitler_min_players: 7,
    reelect_president_max_players: 5,
    themes: [
      {
        id: 'c-suite',
        name: 'C-Suite',
        text: {
          hitler: 'Saboteur',
          liberal: 'Employee',
          liberals: 'Employees',
          liberal_card: 'EMPLOYEE',
          crush_the_liberal_regime: 'Crush the employee morale',
          of_liberal_allegiance: 'Employee',
          fascist: 'Saboteur',
          fascists: 'Saboteurs',
          fascist_card: 'SABOTEUR',
          prevent_the_fascist_regime: 'Prevent the saboteur plot',
          of_fascist_allegiance: 'Saboteur',
          ja: 'Yes',
          nein: 'No',
          policy: 'strategic initiative',
          a_policy: 'a strategic initiative',
          policies: 'initiatives',
          president: 'CEO',
          president_s: 'CEO\'s',
          presidential: 'CEO',
          chancellor: 'Chief Transformation Officer',
          a_politician: 'a board member',
          relieved_of_your_political_duties: 'relieved of your corporate duties',
          relieved_of_their_political_duties: 'relieved of their corporate duties',
          state: 'Company'
        }
      } ,
      {
        id: 'hitler',
        name: 'Secret Hitler',
        text: {
          hitler: 'Hitler',
          liberal: 'Liberal',
          liberals: 'Liberals',
          liberal_card: 'LIBERAL',
          crush_the_liberal_regime: 'Crush the Liberal regime',
          of_liberal_allegiance: 'Liberal',
          fascist: 'Fascist',
          fascists: 'Fascists',
          fascist_card: 'FASCIST',
          prevent_the_fascist_regime: 'Prevent the Fascist regime',
          of_fascist_allegiance: 'Fascist',
          ja: 'Ja!',
          nein: 'Nein!',
          policy: 'policy',
          a_policy: 'a policy',
          policies: 'policies',
          president: 'President',
          president_s: 'President\'s',
          presidential: 'Presidential',
          chancellor: 'Chancellor',
          a_politician: 'a politician',
          relieved_of_your_political_duties: 'relieved of your political duties',
          relieved_of_their_political_duties: 'relieved of their political duties',
          state: 'state'
        }
      }
    ]
  };

  if (typeof window !== "undefined" && window !== null) {
    window.games.data = data;
  }

  if (typeof module !== "undefined" && module !== null) {
    module.exports.data = data;
  }

}).call(this);
